# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $git_metrics\
# $fill\
# $nodejs\
# $cmd_duration $jobs $time\
# $line_break\
# $character"""
#
# [nodejs]
# format = "[$symbol($version )]($style)"
#
# [fill]
# symbol = " "
#
# [directory]
# style = "blue"
# read_only = " "
# truncation_length = 4
# truncate_to_repo = false
#
# [character]
# success_symbol = "[❯](purple)"
# error_symbol = "[❯](red)"
# vicmd_symbol = "[❮](green)"
#
# [git_branch]
# symbol = " "
# format = "[$symbol$branch]($style) "
# style = "bright-black"
#
# [jobs]
# symbol = ""
# style = "bold red"
# number_threshold = 1
# format = "[$symbol]($style)"
#
# [git_status]
# format = '([\[$all_status$ahead_behind\]]($style) )'
# style = "cyan"
#
# [git_state]
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# style = "bright-black"
#
# [git_metrics]
# disabled = false
#
# [cmd_duration]
# format = "[$duration]($style)"
# style = "yellow"
#
# [memory_usage]
# symbol = " "
#
# [rust]
# symbol = " "
#
# [time]
# disabled = false
# style = "bold white"
# format = "[$time]($style)"#



# [aws]
# symbol = "  "
#
# [conda]
# symbol = " "
#
# [dart]
# symbol = " "
# format = "via [$symbol]($style)"
#
# [directory]
# read_only = " "
# truncation_length = 1
#
# [docker_context]
# symbol = " "
#
# [elixir]
# symbol = " "
# format = 'via [$symbol]($style)'
#
# [elm]
# symbol = " "
#
# [git_branch]
# symbol = " "
#
# [golang]
# symbol = " "
# format = 'via [$symbol]($style)'
#
# [hg_branch]
# symbol = " "
#
# [java]
# symbol = " "
# format = 'via [$symbol]($style)'
#
# [julia]
# symbol = " "
#
# [memory_usage]
# symbol = " "
#
# [nim]
# symbol = " "
#
# [nix_shell]
# symbol = " "
#
# [nodejs]
# symbol = " "
# format = 'via [$symbol]($style)'
#
# [package]
# symbol = " "
#
# [perl]
# symbol = " "
#
# [php]
# symbol = " "
#
# [python]
# symbol = " "
# format = 'via [$symbol]($style)'
#
# [ruby]
# symbol = " "
#
# [rust]
# format = 'via [$symbol]($style)'
#
# [scala]
# symbol = " "
#
# [shlvl]
# symbol = " "
#
# [swift]
# symbol = "ﯣ "
# format = 'via [$symbol]($style)'
#
# [c]
# symbol = " "
#
# [git_status]
# disabled = true
#
# # ~/.config/starship.toml


## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# # Setups
# format="$directory$git_branch$character"
# right_format = """$git_status$cmd_duration"""
# add_newline = false 
#
# # Other languages configurations:
# c.disabled = true
# cmake.disabled = true
# haskell.disabled = true
# python.disabled = true
# ruby.disabled = true
# rust.disabled = true
# perl.disabled = true
# package.disabled = true
# lua.disabled = true
# nodejs.disabled = true
# java.disabled = true
# golang.disabled = true
#
# [conda]
# format = ' [$symbol$environment](dimmed green) '
#
# # Prompt symbols 
# [character]
# success_symbol = "[](#a6e3a1 bold)"
# error_symbol = "[](#f38ba8)"
# vicmd_symbol = "[](#f9e2af)"
#
# [directory]
# format = "[]($style)[ ](bg:#161821 fg:#81A1C1)[$path](bg:#161821 fg:#BBC3DF bold)[ ]($style)"
# style = "bg:none fg:#161821"
# truncation_length = 3
# truncate_to_repo=false
#
# [git_branch]
# format = "[]($style)[[ ](bg:#161821 fg:#A2DD9D bold)$branch](bg:#161821 fg:#86AAEC)[ ]($style)"
# style = "bg:none fg:#161821"
#
# [git_status]
# # $all status$ahead_behind
# format = "[]($style)[$all_status$ahead_behind](bg:#161821 fg:#b4befe)[ ]($style)"
# style = "bg:none fg:#161821"
# conflicted = "="
# ahead =	"⇡${count}"
# behind = "⇣${count}"
# diverged = "⇕⇡${ahead_count}⇣${behind_count}"
# up_to_date = ""
# untracked = "?${count}"
# stashed = ""
# modified = "!${count}"
# staged = "+${count}"
# renamed = "»${count}"
# deleted = "${count}"
#
# [cmd_duration]
# min_time = 1
# # duration & style 
# format = "[]($style)[[神](bg:#161821 fg:#eba0ac bold)$duration](bg:#161821 fg:#BBC3DF)[ ]($style)"
# disabled = false
# style = "bg:none fg:#161821"


# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $git_metrics\
# $fill\
# $nodejs\
# $cmd_duration $jobs $time\
# $line_break\
# $character"""
#
# [nodejs]
# format = "[$symbol($version )]($style)"
#
# [fill]
# symbol = " "
#
# [directory]
# style = "blue"
# read_only = " "
# truncation_length = 4
# truncate_to_repo = false
#
# [character]
# success_symbol = "[❯](purple)"
# error_symbol = "[❯](red)"
# vicmd_symbol = "[❮](green)"
#
# [git_branch]
# symbol = " "
# format = "[$symbol$branch]($style) "
# style = "bright-black"
#
# [jobs]
# symbol = ""
# style = "bold red"
# number_threshold = 1
# format = "[$symbol]($style)"
#
# [git_status]
# format = '([\[$all_status$ahead_behind\]]($style) )'
# style = "cyan"
#
# [git_state]
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# style = "bright-black"
#
# [git_metrics]
# disabled = false
#
# [cmd_duration]
# format = "[$duration]($style)"
# style = "yellow"
#
# [memory_usage]
# symbol = " "
#
# [rust]
# symbol = " "
#
# [time]
# disabled = false
# style = "bold white"
# format = "[$time]($style)"#



# [aws]
# symbol = "  "
#
# [conda]
# symbol = " "
#
# [dart]
# symbol = " "
# format = "via [$symbol]($style)"
#
# [directory]
# read_only = " "
# truncation_length = 1
#
# [docker_context]
# symbol = " "
#
# [elixir]
# symbol = " "
# format = 'via [$symbol]($style)'
#
# [elm]
# symbol = " "
#
# [git_branch]
# symbol = " "
#
# [golang]
# symbol = " "
# format = 'via [$symbol]($style)'
#
# [hg_branch]
# symbol = " "
#
# [java]
# symbol = " "
# format = 'via [$symbol]($style)'
#
# [julia]
# symbol = " "
#
# [memory_usage]
# symbol = " "
#
# [nim]
# symbol = " "
#
# [nix_shell]
# symbol = " "
#
# [nodejs]
# symbol = " "
# format = 'via [$symbol]($style)'
#
# [package]
# symbol = " "
#
# [perl]
# symbol = " "
#
# [php]
# symbol = " "
#
# [python]
# symbol = " "
# format = 'via [$symbol]($style)'
#
# [ruby]
# symbol = " "
#
# [rust]
# format = 'via [$symbol]($style)'
#
# [scala]
# symbol = " "
#
# [shlvl]
# symbol = " "
#
# [swift]
# symbol = "ﯣ "
# format = 'via [$symbol]($style)'
#
# [c]
# symbol = " "
#
# [git_status]
# disabled = true
#
# # ~/.config/starship.toml


## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# # Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration"""
add_newline = false 

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = "[](#a6e3a1 bold)"
error_symbol = "[](#f38ba8)"
vicmd_symbol = "[](#f9e2af)"

[directory]
format = "[]($style)[ ](bg:#161821 fg:#81A1C1)[$path](bg:#161821 fg:#BBC3DF bold)[ ]($style)"
style = "bg:none fg:#161821"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:#161821 fg:#A2DD9D bold)$branch](bg:#161821 fg:#86AAEC)[ ]($style)"
style = "bg:none fg:#161821"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:#161821 fg:#b4befe)[ ]($style)"
style = "bg:none fg:#161821"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[神](bg:#161821 fg:#eba0ac bold)$duration](bg:#161821 fg:#BBC3DF)[ ]($style)"
disabled = false
style = "bg:none fg:#161821"

# "$schema" = 'https://starship.rs/config-schema.json'
#
# add_newline = true 
#
# format = """$status$directory
#  """
#
# right_format = "$git_branch $git_metrics"
#
# [status]
# # symbol          = " [▟](bg:#282028 fg:#0c4f63)[ 󰘧 ](bg:#0c4f63 fg:#dbd7d2)[▛](bg:#282828 fg:#0c4f63)"
# # success_symbol  = " [▟](bg:#282028 fg:#dbd7d2)[ 󰘧 ](bg:#dbd7d2 fg:#282828)[▛](bg:#282828 fg:#dbd7d2)"
# symbol          = " [▟](bg:#282028 fg:#0c4f63)[ 󰘧 ](bg:#0c4f63 fg:#dbd7d2)[▛](bg:#282828 fg:#0c4f63)"
# success_symbol  = " [▟](bg:#282028 fg:#dbd7d2)[ 󰘧 ](bg:#dbd7d2 fg:#282828)[▛](bg:#282828 fg:#dbd7d2)"
# disabled = false
# format = '$symbol'
#
# [directory]
# disabled = false
# format = " [▟](bg:#282028 fg:#dbd7d2)[   ┃ $path ](bg:#dbd7d2 fg:#282828)[▛](bg:#282828 fg:#dbd7d2) "
#
# [git_branch]
# symbol = ''
# format = '[$symbol $branch](fg:#6f7789 bg:#282028) '
#
# [git_metrics]
# disabled = false
# only_nonzero_diffs = false
# format = '[▟](bg:#282028 fg:#dbd7d2)[ + $added ](fg:#282828 bg:#dbd7d2)[┃](bg:#dbd7d2 fg:#282828)[ - $deleted ](fg:#282828 bg:#dbd7d2)[▛](bg:#282828 fg:#dbd7d2)'

